---
title: " Analysis Paired Burned Unburned"
author: "Anna Talucci"
date: "2024-02-23"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
Figures looking at measured versus predicted


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(ggnewscale)
library(ggthemes)
```

# Plot themes
```{r}
comp_theme = theme_bw() + theme(legend.position = "bottom") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"))
```

# Data

## Predicted measurements

## Predicted measurements

```{r}
datacubePred = read_csv("../data/dataCube/PermafrostFireDatacubeFinal.csv")
```

```{r}
datacubePred
```

# Aggregate

```{r}
( aggregate = datacubePred %>% 
  group_by(resBiome, resName, submitNm, distur, permaExtent, paired, fireYr, tsf, tsfClass) %>%
  summarise(n = n(),
            mean = mean(predDepth),
            sd   = sd(predDepth, na.rm=TRUE),
            se   = sd / sqrt(n))
)
```
# Add factor levels for TSF


```{r}
aggregate$tsfClass = factor(aggregate$tsfClass, levels = c( "unburned", "0-3", "4-10", "11-20", "21-40", ">40"))
```






```{r}
depthChangeBiome$permaExtent <- fct_recode(depthChangeBiome$permaExtent, "Continuous"= "C", "Discontinuous"="D", "Sporadic"="S")
```








#  Boxplots

## Burned Unburned
```{r}
( pairedBoxplots = ggplot(aggregate, aes(x = distur, y=mean, color=distur)) +
  geom_boxplot() +
  scale_color_manual(values=c('#fc8d59', '#91bfdb'), name="", labels = c('Burned', 'Unburned')) +
    scale_y_reverse() +
  labs(x="", y="Depth (cm)") +
  facet_wrap(~resName, scales = "free_y") +
  comp_theme +
     theme(axis.text.y = element_text(size=5),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
    theme(
   strip.background = element_rect(
     color="white", fill="white", size=1.5, linetype="solid"
     )) +
    theme(strip.text.x = element_text(size = 5))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateBurnedUnburnedBoxPlot.png", plot = pairedBoxplots, width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```




# TSF Burned Unburned Mean with SE

```{r}
( plotBiomeTSF <- ggplot(aggregate, aes(x = tsfClass, y=mean, color=distur)) +
    geom_boxplot() +
      scale_color_manual(values=c('#fc8d59', '#91bfdb'), name="", labels = c('Burned', 'Unburned')) +
    scale_y_reverse() +
  labs(x="Time since fire", y="Depth (cm)") +
    #facet_grid(vars(resBiome), vars(permaExtent), scales="free") +
  facet_wrap(~resBiome + permaExtent, scales = "free") +
theme_bw() + 
  theme(legend.position = c(.8, .3)) +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black")) +
    theme(
          axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5, angle=45),
          strip.background = element_rect( color="white", fill="white", size=1.5, linetype="solid" )) +
    theme(strip.text.x = element_text(size = 6))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateBurnedUnburnedBiomeTsf.png", plot = plotBiomeTSF, width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```






