---
title: " Analysis Paired Burned Unburned"
author: "Anna Talucci"
date: "2024-02-23"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
Figures looking at measured versus predicted


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(ggnewscale)
library(ggthemes)
```

# Plot themes
```{r}
comp_theme = theme_bw() + theme(legend.position = "bottom") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"))
```

# Data

## Predicted measurements
'../outputs/dataCube/AggregatedBurnUnburn.csv')
```{r}
aggregate = read_csv("../data/aggregate/AggregatedBurnUnburnPairs.csv")
```
```{r}
aggregateBiome = read_csv("../data/aggregate/AggregatedBurnUnburnBiome.csv")
```

```{r}
depthChange = read_csv("../data/aggregate/AggregatedDepthChange.csv")
```


```{r}
depthChangeBiome = read_csv("../data/aggregate/AggregatedDepthChangeBiome.csv")
```
# Add factor levels for TSF

```{r}
aggregate$tsf = factor(aggregate$tsf, levels = c("u", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","19", "20", "21", "29", "30", "31", "32",  "33", "35", "36", "39", "40", "41", "45", "46", "47", "48", "49", "50", "52", "114"))
```

```{r}
unique(aggregate$tsf)
```

```{r}
aggregateBiome$tsf = factor(aggregateBiome$tsf, levels = c("u", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","19", "20", "21", "29", "30", "31", "32",  "33", "35", "36", "39", "40", "41", "45", "46", "47", "48", "49", "50", "52", "114"))
```

```{r}
unique(aggregateBiome$tsf)
```

```{r}
aggregateBiome$permaExtent <- fct_recode(aggregateBiome$permaExtent, "Continuous"= "C", "Discontinuous"="D", "Sporadic"="S")
```

```{r}
unique(aggregateBiome$permaExtent)
```

```{r}
depthChange$tsf = factor(depthChange$tsf, levels = c("u", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","19", "20", "21", "29", "30", "31", "32",  "33", "35", "36", "39", "40", "41", "45", "46", "47", "48", "49", "50", "52", "114"))
```

```{r}
unique(depthChange$tsf)
```

```{r}
depthChangeBiome$tsf = factor(depthChangeBiome$tsf, levels = c("u", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","19", "20", "21", "29", "30", "31", "32",  "33", "35", "36", "39", "40", "41", "45", "46", "47", "48", "49", "50", "52", "114"))
```

```{r}
unique(depthChange$tsf)
```

```{r}
unique(depthChangeBiome$permaExtent)
```

```{r}
depthChangeBiome$permaExtent <- fct_recode(depthChangeBiome$permaExtent, "Continuous"= "C", "Discontinuous"="D", "Sporadic"="S")
```

```{r}
unique(depthChangeBiome$permaExtent)
```

# View data frames

```{r}
aggregate 
aggregateBiome
depthChange
depthChangeBiome
```





#  Boxplots

## Burned Unburned
```{r}
( pairedBoxplots = ggplot(aggregate, aes(x = distur, y=mean, color=distur)) +
  geom_boxplot() +
  scale_color_manual(values=c('#fc8d59', '#91bfdb'), name="", labels = c('Burned', 'Unburned')) +
    scale_y_reverse() +
  labs(x="", y="Depth (cm)") +
  facet_wrap(~resName, scales = "free_y") +
  comp_theme +
     theme(axis.text.y = element_text(size=5),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
    theme(
   strip.background = element_rect(
     color="white", fill="white", size=1.5, linetype="solid"
     )) +
    theme(strip.text.x = element_text(size = 5))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateBurnedUnburnedBoxPlot.png", plot = pairedBoxplots, width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```




# TSF Burned Unburned Mean with SE

```{r}
( plotBiomeTSF <- ggplot(aggregateBiome, aes(x = tsf, y=mean, color=distur, group=tsf)) +
    geom_point() +
      scale_color_manual(values=c('#fc8d59', '#91bfdb'), name="", labels = c('Burned', 'Unburned')) +
    scale_y_reverse() +
  labs(x="Time since fire", y="Depth (cm)") +
    #facet_grid(vars(resBiome), vars(permaExtent), scales="free") +
  facet_wrap(~resBiome + permaExtent, scales = "free") +
theme_bw() + 
  theme(legend.position = c(.8, .3)) +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black")) +
    theme(
          axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5, angle=45),
          strip.background = element_rect( color="white", fill="white", size=1.5, linetype="solid" )) +
    theme(strip.text.x = element_text(size = 6))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateBurnedUnburnedBiomeTsf.png", plot = plotBiomeTSF, width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```


```{r}
depthChangeBiome
```
# By Biome
```{r}
( plotDepthChangeBiome = ggplot(depthChangeBiome, aes(x = tsf, y=depthChange)) +
  geom_hline(yintercept=0, color="gray", size = 3, alpha = .5) + 
   geom_point(color='#5e4fa2', size = 3, shape = 21) +

      #scale_color_manual(values=c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e','#e6ab02','#a6761d'), name="") +
  scale_y_reverse() +
  labs(x="Time since fire", y="Change in depth (cm)") +
     #facet_grid(vars(resBiome), vars(permaExtent), scales="free") +
  facet_wrap(~resBiome + permaExtent, scales = "free") +
  comp_theme +
    theme(legend.position = "none",
          axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5, angle=45),
          strip.background = element_rect( color="white", fill="white", size=1.5, linetype="solid" )) +
    theme(strip.text.x = element_text(size = 6))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateDepthChangeTsfBiome.png", plot = plotDepthChangeBiome,  width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```


# By Ecozone
```{r}
( plotDepthChange = ggplot(depthChange, aes(x = tsf, y=depthChange)) +
  geom_hline(yintercept=0, color="gray", size = 3, alpha = .5) + 
   geom_point(color='#5e4fa2', size = 3, shape = 21) +

      #scale_color_manual(values=c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e','#e6ab02','#a6761d'), name="") +
  scale_y_reverse() +
  labs(x="Time since fire", y="Change in depth (cm)") +
  facet_wrap(~resName, scales = "free") +
  comp_theme +
    theme(legend.position = "none",
          axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5, angle=45),
          strip.background = element_rect( color="white", fill="white", size=1.5, linetype="solid" )) +
    theme(strip.text.x = element_text(size = 6))
)
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/AggregateDepthChangeTsfEcozone.png", plot = plotDepthChange,  width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```