---
title: "Validation quantify uncertainty Test"
author: "Anna Talucci"
date: "2024-10-16"
output: html_document
---


# clear environment

```{r}
rm(list=ls())
```

# Overview

validation quantify uncertainty


# Packages

```{r}
library(tidyverse)
library(ggpubr)
library(ggnewscale)
library(ggthemes)
library(ggpmisc)
library(cowplot)
library(Metrics) 
library(sf)
library(scales)
```
# Plot themes

```{r}
comp_theme = theme_bw() +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 10, hjust = 0.5, vjust = 1.1),
          axis.title.x = element_text(size = 10, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 9, color = "black"),
        axis.text.y = element_text(size = 9, color = "black"))
```


# Data

```{r}
data = read_csv("../outputs/validationPredict/validationPredictHollowayBreenTest.csv")
```


```{r}
data
```
```{r}
unique(data$plot)
```

```{r}
unique(data$site)
```



```{r}
unique(data$site)
```

# Split by Early and late

```{r}
( early = data %>% 
    filter(msrType=="thaw") %>%
    dplyr::select(-A_sum, -A, -B_sum, -B, -C, -resName, -resBmNm))
( late = data %>% 
    filter(msrType=="active") %>% 
    dplyr::select(site:year, msrDpth, dateGrp, resName, resBmNm) %>%
    rename(msrDepthLate = msrDpth))
```

"b1"     "b12"    "b13"    "b15"    "b16"    "b5"     "b8"     "b9"     "UB3"    "b14"    "UB2"   
[12] "DR"     "GC"     "MP85"   "MP86"   "ML"     "UbMp80"

# Validation Data

```{r}
( valData = early %>% 
    full_join(., late, by=c("site", "plot", "dateGrp", "year")) %>%
    mutate(disturbance = ifelse(site %in% c("UB2", "UB3", "UbMp80"), "unburned", "burned")) %>%
    mutate(residualError = msrDepthLate - predDepth) %>% 
    mutate(relativeError = (msrDepthLate - predDepth) / msrDepthLate * 100) %>% 
    drop_na(msrDepthLate) %>% 
    drop_na(predDepth) 
)
```



```{r}
names(valData)
```


### Summarize
```{r}
valData %>% 
  group_by(resBmNm, disturbance, lastNm) %>%
  summarise(meanResidualError = mean(residualError),
            meanPercentError = mean(relativeError),
            n=n()) %>%
  drop_na(meanResidualError) 

```

```{r}
unburnTundra = valData %>% filter(disturbance == "unburned") %>% filter(resBmNm == "Tundra")
burnTundra = valData %>% filter(disturbance == "burned") %>% filter(resBmNm == "Tundra")
unburnBoreal = valData %>% filter(disturbance == "unburned") %>% filter(resBmNm == "Boreal Forests/Taiga")
( burnBoreal = valData %>% filter(disturbance == "burned") %>% filter(resBmNm == "Boreal Forests/Taiga") %>% drop_na(predDepth) )
```
```{r}
model_unburnTundra = lm(predDepth ~ msrDepthLate, data = unburnTundra) 
model_burnTundra = lm(predDepth ~ msrDepthLate, data = burnTundra)
model_unburnBoreal = lm(predDepth ~ msrDepthLate, data = unburnBoreal) 
model_burnBoreal = lm(predDepth ~ msrDepthLate, data = burnBoreal)
```

```{r}
summary(model_unburnTundra)
summary(model_burnTundra)
summary(model_unburnBoreal)
summary(model_burnBoreal)
```

```{r}
predicted_ut <- predict(model_unburnTundra) # Get predicted values from the model
residuals_ut <- unburnTundra$predDepth - predicted_ut # Calculate residuals
rmse_ut <- sqrt(mean(residuals_ut^2)) # Calculate RMSE
print(paste("Unburned Tundra RMSE:", rmse_ut)) # Print RMSE
```

```{r}
predicted_bt <- predict(model_burnTundra) # Get predicted values from the model
residuals_bt <- burnTundra$predDepth - predicted_bt # Calculate residuals
rmse_bt <- sqrt(mean(residuals_bt^2)) # Calculate RMSE
print(paste("Burned Tundra RMSE:", rmse_bt)) # Print RMSE
```

```{r}
predicted_ub <- predict(model_unburnBoreal) # Get predicted values from the model
residuals_ub <- unburnBoreal$predDepth - predicted_ub # Calculate residuals
rmse_ub <- sqrt(mean(residuals_ub^2)) # Calculate RMSE
print(paste("Unburned Boreal RMSE:", rmse_ub)) # Print RMSE
```

```{r}
predicted_bb <- predict(model_burnBoreal)  # Get predicted values from the model
residuals_bb <- burnBoreal$predDepth - predicted_bb  # Calculate residuals
rmse_bb <- sqrt(mean(residuals_bb^2)) # Calculate RMSE
print(paste("burned Boreal RMSE:", rmse_bb)) # Print RMSE
```

# Plots

## unburned
color="#3d5a80"
```{r}
(unburned = valData %>% filter(disturbance=="unburned") %>% drop_na(msrDepthLate) %>% drop_na(predDepth) )
```
```{r}
max(unburned$predDepth)
max(unburned$msrDepthLate)
min(unburned$predDepth)
min(unburned$msrDepthLate)
```

```{r}
( observPredPlotUnburned = ggplot(unburned, aes(x=msrDepthLate, y=predDepth)) +
  geom_abline (slope=1, intercept = 0, linetype = "solid", color="#f7aa58")+
    geom_point(size =1, shape=1, aes(color=resBmNm)) +
    scale_color_manual(values=c('#59a89c', '#a559aa'), name="Biome", labels=c("Boreal", "Tundra")) +
  #stat_poly_eq() +
  #stat_poly_line() +
    xlim(29, 170) + ylim(29, 170) +
 comp_theme +
   theme(legend.position = "none") + 
   labs(x= "Observed active layer thickness (cm)", y="Estimated active\nlayer thickness (cm)", title="Unburned") 
)
```

## Burned
```{r}
(burned = valData %>% filter(disturbance=="burned") %>% drop_na(msrDepthLate) %>% drop_na(predDepth) )
```
```{r}
max(burned$predDepth)
max(burned$msrDepthLate)
min(burned$predDepth)
min(burned$msrDepthLate)
```
```{r}
( observPredPlotBurned = ggplot(burned, aes(x=msrDepthLate, y=predDepth)) +
  geom_abline (slope=1, intercept = 0, linetype = "solid", color="#f7aa58")+
   geom_point(size = 1, shape=1, aes(color=resBmNm)) +
    scale_color_manual(values=c('#59a89c', '#a559aa'), name="Biome", labels=c("Boreal", "Tundra")) +
  #stat_poly_eq() +
  #stat_poly_line() +
    xlim(25, 212) + ylim(25, 212) +
 comp_theme +
   theme(legend.position = "none") + 
   labs(x= "Observed active layer thickness (cm)", y="Estimated active\nlayer thickness (cm)", title="Burned") 
)
```

## All data plot


```{r}
( residualErrorPlot = ggplot(valData, aes(x=site, y=residualError)) +
  geom_hline(yintercept=0, color="gray", size = 3, alpha = .5) +
  geom_point(size =1, shape=1, aes(color=resBmNm)) +
    scale_color_manual(values=c('#59a89c', '#a559aa'), name="Biome", labels=c("Boreal", "Tundra")) +
 comp_theme +
   theme(legend.position = c(.7, .9)) +
   guides(color=guide_legend(ncol=2, title.position = "left")) +
   labs(x= "Plot", y="Residual Error (cm)") +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  annotate(
    'text',
    x = 15.8,
    y = 80,
    label = 'Underestimate',
    fontface = 'plain', 
    size = 3,
    angle= 90,
    color = "gray"
  )  +
  annotate(
    'curve',
    x = 16.3, # Play around with the coordinates until you're satisfied
    y = 20,
    yend = 120,
    xend = 16.3,
    linewidth = .8,
    curvature = 0,
    color="gray",
    arrow = arrow(length = unit(0.4, 'cm'))
  ) +
  annotate(
    'text',
    x = 15.8,
    y = -60,
    label = 'Overestimate',
    fontface = 'plain', 
    size = 3,
    angle= 90,
    color = "gray"
  )  +
  annotate(
    'curve',
    x = 16.3, # Play around with the coordinates until you're satisfied
    y = -20,
    yend = -120,
    xend = 16.3,
    linewidth = .8,
    curvature = 0,
    color="gray",
    arrow = arrow(length = unit(0.4, 'cm'))
  )
)
```


# Combine plots


```{r}
( top = cowplot::plot_grid(observPredPlotUnburned, observPredPlotBurned, ncol=2, labels = c("A", "B"))
)

( bottom = cowplot::plot_grid(residualErrorPlot, ncol=1, labels = "C")
)

( combineTopBottom = cowplot::plot_grid(top, bottom, ncol=1) )
```


```{r eval=FALSE, include=FALSE}
ggsave("../figures/ValidationPlotsBurnUnburn.png", plot = combineTopBottom, dpi = 600, width = 6, height = 6, bg='white')
```



